coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
    changes: false
comment:
  layout: "condensed_header, condensed_files, condensed_footer" # add "condensed_" to "header", "files" and "footer"
  hide_project_coverage: true # set to true
