"""
    Rt_3H_Caskey1979_para_c

Diffusion data of Tritium in rutile. With anhydrous conditions and parallel to c-axis. Calibrated between 155-300°C.
From Caskey et al. (1974) (https://doi.org/10.1016/0025-5416(74)90003-2).
"""
function Rt_3H_Caskey1979_para_c()
    data = DiffusionData(
        Name = "Tritium diffusion in Rutile (parallel to c-axis and anhydrous conditions) | Caskey et al. (1974)",
        Phase = "Rutile",
        Formula = "TiO2",
        Species = "3H",
        Orientation = "Ξc",
        Crystallography = "Tetragonal",
        Fluid = "Anhydrous",
        D0 = 7.5e-6cm^2 / s,
        Ea = 9040u"cal / mol",
        Charge = 1,  # charge of the cation
        T_range_min = 155C,
        T_range_max = 300C
    )
    info = MaterialParamsInfo(;
        Comment = "Checked values by ML (05.02.25)",
        BibTex_Reference = "
          @article{Caskey1974,
            abstract = {Tritium diffusion in single crystals of rutile (TiO2) was measured at temperatures between 155° and 300° C. Diffusivities were calculated from concentration profiles obtained from microdensitometer traces of autoradiographs generated by the β-decay of the tritium. Diffusivity is anisotropic with estimated diffusion equations of: Dc = 7.5 × 10-6 exp(-9040/ RT), and Da = 2.7 × 10-6 exp(-13,100/RT). © 1974.},
            author = {G. R. Caskey},
            doi = {10.1016/0025-5416(74)90003-2},
            issn = {00255416},
            issue = {2},
            journal = {Materials Science and Engineering},
            pages = {109-114},
            title = {Diffusion of tritium in rutile (TiO2)},
            volume = {14},
            year = {1974},
            }
          ",
    )

    return data, info
end


"""
    Rt_3H_Caskey1979_perp_c

Diffusion data of Tritium in rutile. With anhydrous conditions and perpendicular to c-axis. Calibrated between 155-300°C.
From Caskey et al. (1974) (https://doi.org/10.1016/0025-5416(74)90003-2).
"""
function Rt_3H_Caskey1979_perp_c()
    data = DiffusionData(
        Name = "Tritium diffusion in Rutile (perpendicular to c-axis and anhydrous conditions) | Caskey et al. (1974)",
        Phase = "Rutile",
        Formula = "TiO2",
        Species = "3H",
        Orientation = "⊥c",
        Crystallography = "Tetragonal",
        Fluid = "Anhydrous",
        D0 = 2.7e-6cm^2 / s,
        Ea = 13100u"cal / mol",
        Charge = 1,  # charge of the cation
        T_range_min = 155C,
        T_range_max = 300C
    )
    info = MaterialParamsInfo(;
        Comment = "Checked values by ML (05.02.25)",
        BibTex_Reference = "
          @article{Caskey1974,
            abstract = {Tritium diffusion in single crystals of rutile (TiO2) was measured at temperatures between 155° and 300° C. Diffusivities were calculated from concentration profiles obtained from microdensitometer traces of autoradiographs generated by the β-decay of the tritium. Diffusivity is anisotropic with estimated diffusion equations of: Dc = 7.5 × 10-6 exp(-9040/ RT), and Da = 2.7 × 10-6 exp(-13,100/RT). © 1974.},
            author = {G. R. Caskey},
            doi = {10.1016/0025-5416(74)90003-2},
            issn = {00255416},
            issue = {2},
            journal = {Materials Science and Engineering},
            pages = {109-114},
            title = {Diffusion of tritium in rutile (TiO2)},
            volume = {14},
            year = {1974},
            }
          ",
    )

    return data, info
end


"""
    Rt_3H_Cathcart1979_perp_c

Diffusion data of Tritium in rutile. With anhydrous conditions and perpendicular to c-axis. Calibrated between 250-900°C.
From Cathcart et al. (1979) (https://doi.org/110.1063/1.326490).
"""
function Rt_3H_Cathcart1979_perp_c()
    data = DiffusionData(
        Name = "Tritium diffusion in Rutile (perpendicular to c-axis and anhydrous conditions) | Cathcart et al. (1979)",
        Phase = "Rutile",
        Formula = "TiO2",
        Species = "3H",
        Orientation = "⊥c",
        Crystallography = "Tetragonal",
        Fluid = "Anhydrous",
        D0 = 1.77e-2cm^2 / s,
        log_D0_1σ = 4.3NoUnits, 
        Ea = 107kJ/mol,
        Ea_1σ = 4kJ/mol,
        Charge = 1,  # charge of the cation
        T_range_min = 250C,
        T_range_max = 900C
    )
    info = MaterialParamsInfo(;
        Comment = "Checked values by ML (05.02.25)",
        BibTex_Reference = "
          @article{Cathcart1979,
            abstract = {The diffusivity of tritium in rutile single crystals has been measured parallel to the a and c axes in the temperature range 250-900 °C. Raman-scattering measurements were also made to aid in identifying a nonpolar tritium species involved in the diffusion process. Two species, OT- ions and T2 molecules, are involved in tritium migration. The OT - ions dissociate preceding each tritium jump. Along the a axis the T2 molecules diffuse four orders of magnitude slower than the T + ions associated with OT-. No dependency of the tritium diffusivity upon the rutile defect structure was observed.},
            author = {J. V. Cathcart and R. A. Perkins and J. B. Bates and L. C. Manley},
            doi = {10.1063/1.326490},
            issn = {00218979},
            issue = {6},
            journal = {Journal of Applied Physics},
            pages = {4110-4119},
            title = {Tritium diffusion in rutile (TiO2)},
            volume = {50},
            year = {1979},
            }
          ",
    )

    return data, info
end

"""
    Rt_3H_Cathcart1979_para_c

Diffusion data of Tritium in rutile. With anhydrous conditions and parallel to c-axis. Calibrated between 250-900°C.
From Cathcart et al. (1979) (https://doi.org/110.1063/1.326490).
"""
function Rt_3H_Cathcart1979_para_c()
    data = DiffusionData(
        Name = "Tritium diffusion in Rutile (parallel to c-axis and anhydrous conditions) | Cathcart et al. (1979)",
        Phase = "Rutile",
        Formula = "TiO2",
        Species = "3H",
        Orientation = "Ξc",
        Crystallography = "Tetragonal",
        Fluid = "Anhydrous",
        D0 = 0.0085cm^2 / s,
        log_D0_1σ = 4.1NoUnits, 
        Ea = 72.2kJ/mol,
        Ea_1σ = 6.2kJ/mol,
        Charge = 1,  # charge of the cation
        T_range_min = 250C,
        T_range_max = 900C
    )
    info = MaterialParamsInfo(;
        Comment = "Checked values by ML (05.02.25)",
        BibTex_Reference = "
          @article{Cathcart1979,
            abstract = {The diffusivity of tritium in rutile single crystals has been measured parallel to the a and c axes in the temperature range 250-900 °C. Raman-scattering measurements were also made to aid in identifying a nonpolar tritium species involved in the diffusion process. Two species, OT- ions and T2 molecules, are involved in tritium migration. The OT - ions dissociate preceding each tritium jump. Along the a axis the T2 molecules diffuse four orders of magnitude slower than the T + ions associated with OT-. No dependency of the tritium diffusivity upon the rutile defect structure was observed.},
            author = {J. V. Cathcart and R. A. Perkins and J. B. Bates and L. C. Manley},
            doi = {10.1063/1.326490},
            issn = {00218979},
            issue = {6},
            journal = {Journal of Applied Physics},
            pages = {4110-4119},
            title = {Tritium diffusion in rutile (TiO2)},
            volume = {50},
            year = {1979},
            }
          ",
    )

    return data, info
end


"""
    Rt_H_Johnson1975_para_c

Diffusion data of H in rutile. With anhydrous conditions and parallel to c-axis. 
Calibrated between 125-750°C.
From Johnson et al. (1975) (https://doi.org/10.1063/1.322206).
"""
function Rt_H_Johnson1975_para_c()
    data = DiffusionData(
        Name = "H diffusion in Rutile (parallel to c-axis and anhydrous conditions) | Johnson et al. (1975)",
        Phase = "Rutile",
        Formula = "TiO2",
        Species = "H",
        Orientation = "Ξc",
        Crystallography = "Tetragonal",
        Fluid = "Anhydrous",
        D0 = 1.8e-3cm^2 / s,
        log_D0_1σ = log(0.8e-3)NoUnits, 
        Ea = (0.59u"eV" * Unitful.Na),
        Ea_1σ = (0.02u"eV" * Unitful.Na),
        Charge = 1,  # charge of the cation
        T_range_min = 125C,
        T_range_max = 750C
    )
    info = MaterialParamsInfo(;
        Comment = "Checked values by ML (05.02.25)",
        BibTex_Reference = "
          @article{Johnson1975,
            abstract = {Measurements of H and D diffusion in TiO2, using the isotope exchange technique described in the preceding paper, are reported. Use of this technique resulted in diffusion which was accurately described by Fick's law with a constant diffusion coefficient, as predicted theoretically, in sharp contrast to single ion diffusion, where dramatic departures from classical diffusion theory were observed. The measured diffusion coefficients for H were 1.8×10-3 exp(-0.59eV/kT) and 3.8×10-1 exp(-1.28eV/kT) and 3.8×10-1 exp(-1.28eV/kT) cm2/sec for diffusion ∥ and ⊥ to the c axis, respectively. Ionic conductivity measurements are reported, which agree well with the bulk diffusion measurements, and permitted us to extend the temperature range of the measurements for c-axis diffusion from 125 to 750°C, corresponding to a range of more than four orders of magnitude in D. The measured diffusion parameters were found to be essentially independent of sample purity, although it was observed that significant concentrations of lattice defects sharply inhibited H diffusion.},
            author = {O. W. Johnson and S. H. Paek and J. W. Deford},
            doi = {10.1063/1.322206},
            issn = {00218979},
            issue = {3},
            journal = {Journal of Applied Physics},
            pages = {1026-1033},
            title = {Diffusion of H and D in TiO2: Suppression of internal fields by isotope exchange},
            volume = {46},
            year = {1975},
            }
          ",
    )

    return data, info
end


"""
    Rt_H_Johnson1975_perp_c

Diffusion data of H in rutile. With anhydrous conditions and perpendicular to c-axis. 
Calibrated between 125-750°C. From Johnson et al. (1975) (https://doi.org/10.1063/1.322206).
"""
function Rt_H_Johnson1975_perp_c()
    data = DiffusionData(
        Name = "H diffusion in Rutile (perpendicular to c-axis and anhydrous conditions) | Johnson et al. (1975)",
        Phase = "Rutile",
        Formula = "TiO2",
        Species = "H",
        Orientation = "⊥c",
        Crystallography = "Tetragonal",
        Fluid = "Anhydrous",
        D0 = 3.8e-1cm^2 / s,
        log_D0_1σ = log(2.0e-1)NoUnits, 
        Ea = (1.28u"eV" * Unitful.Na),
        Ea_1σ = (0.05u"eV" * Unitful.Na),
        Charge = 1,  # charge of the cation
        T_range_min = 125C,
        T_range_max = 750C
    )
    info = MaterialParamsInfo(;
        Comment = "Checked values by ML (05.02.25)",
        BibTex_Reference = "
          @article{Johnson1975,
            abstract = {Measurements of H and D diffusion in TiO2, using the isotope exchange technique described in the preceding paper, are reported. Use of this technique resulted in diffusion which was accurately described by Fick's law with a constant diffusion coefficient, as predicted theoretically, in sharp contrast to single ion diffusion, where dramatic departures from classical diffusion theory were observed. The measured diffusion coefficients for H were 1.8×10-3 exp(-0.59eV/kT) and 3.8×10-1 exp(-1.28eV/kT) and 3.8×10-1 exp(-1.28eV/kT) cm2/sec for diffusion ∥ and ⊥ to the c axis, respectively. Ionic conductivity measurements are reported, which agree well with the bulk diffusion measurements, and permitted us to extend the temperature range of the measurements for c-axis diffusion from 125 to 750°C, corresponding to a range of more than four orders of magnitude in D. The measured diffusion parameters were found to be essentially independent of sample purity, although it was observed that significant concentrations of lattice defects sharply inhibited H diffusion.},
            author = {O. W. Johnson and S. H. Paek and J. W. Deford},
            doi = {10.1063/1.322206},
            issn = {00218979},
            issue = {3},
            journal = {Journal of Applied Physics},
            pages = {1026-1033},
            title = {Diffusion of H and D in TiO2: Suppression of internal fields by isotope exchange},
            volume = {46},
            year = {1975},
            }
          ",
    )

    return data, info
end