# Note: this workflow is copied from the Trixi.jl package
name: Documentation
on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths-ignore:
      - '.github/workflows/SpellCheck.yml'
      - '.github/workflows/blank.yml'
      - '.github/workflows/TagBot.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/SpellCheck.yml'
      - '.github/workflows/blank.yml'
      - '.github/workflows/TagBot.yml'
  workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
